#!/bin/bash
#
#  This file is part of Planning-Trace-Alignment.
#
#  Planning-Trace-Alignment is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Planning-Trace-Alignment is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with Planning-Trace-Alignment.  If not, see <https://www.gnu.org/licenses/>.
#
#

cd seq-opt-symba-2
date1=$(date +%s%N | cut -b1-13)
searchtime=0
trace="$1"
domain="Conformance_Checking/domain$trace.pddl"
problem="Conformance_Checking/problem$trace.pddl"
./plan $domain $problem out.txt
date2=$(date +%s%N | cut -b1-13)
diff=$(($date2-$date1))
#echo $date1
#echo $date2
echo "the duration for trace #$trace is: $diff ms."
