name: Trace-Alignment Code CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget python3-pip
      - name: Check File Headers
        run: python3 ./scripts/check_copyright_notice.py
          
      - name: Install cudd, mona, lydia
        run: ./scripts/_ci-install-dependencies-ubuntu.sh
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
